// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHVY4BkADf37Tb9JPd4-K4xjjil1TBleY',
    appId: '1:14197951991:web:113de3a34d88fde52372f2',
    messagingSenderId: '14197951991',
    projectId: 'phinom-coffee',
    authDomain: 'phinom-coffee.firebaseapp.com',
    storageBucket: 'phinom-coffee.firebasestorage.app',
    measurementId: 'G-73407XVH4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZSu6COYp-iS3CyBPA55PiuUwThqK50U',
    appId: '1:14197951991:android:bb83499a4a46d89d2372f2',
    messagingSenderId: '14197951991',
    projectId: 'phinom-coffee',
    storageBucket: 'phinom-coffee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwQeeO3LlLgyVA_hSOzYaPqsuif4pTTH0',
    appId: '1:14197951991:ios:32d2c0d7dcceaaf92372f2',
    messagingSenderId: '14197951991',
    projectId: 'phinom-coffee',
    storageBucket: 'phinom-coffee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwQeeO3LlLgyVA_hSOzYaPqsuif4pTTH0',
    appId: '1:14197951991:ios:32d2c0d7dcceaaf92372f2',
    messagingSenderId: '14197951991',
    projectId: 'phinom-coffee',
    storageBucket: 'phinom-coffee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHVY4BkADf37Tb9JPd4-K4xjjil1TBleY',
    appId: '1:14197951991:web:d4175d335384565a2372f2',
    messagingSenderId: '14197951991',
    projectId: 'phinom-coffee',
    authDomain: 'phinom-coffee.firebaseapp.com',
    storageBucket: 'phinom-coffee.firebasestorage.app',
    measurementId: 'G-QVQCGKNGFY',
  );

}
